# Generated by Django 3.0 on 2019-12-26 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2019, 12, 26, 19, 21, 18, 12903, tzinfo=utc))),
                ('type_blog', models.CharField(choices=[('en', 'entertainment'), ('ls', 'lifestyle'), ('edu', 'education'), ('play', 'sports')], max_length=10)),
                ('blog_des', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
